controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint"]

    wheel_separation: 0.50
    wheel_radius: 0.10

    wheels_per_side: 1

    open_loop: true
    position_feedback: false

    odom_frame_id: odom
    base_frame_id: base_link

    # Disabled for ZED-odom mode to avoid duplicate odom->base_link TF.
    enable_odom_tf: false

    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
