twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: /cmd_vel_teleop
        timeout: 0.4
        priority: 100
      nav:
        topic: /cmd_vel_nav
        timeout: 0.4
        priority: 50
    locks:
      estop:
        topic: /cmd_vel_lock
        timeout: 0.0
        priority: 255
