controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["left_front_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint"]

    # Real geometry: 27 in track width, 4 in wheel radius
    wheel_separation: 0.6858
    wheel_radius: 0.1016

    wheels_per_side: 1

    # With no real wheel feedback (or unreliable feedback due to duplicate IDs),
    # run open-loop odometry from commanded velocities.
    open_loop: true

    # We'll be providing velocity state as "the last command" (open loop feedback).
    position_feedback: false

    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true

    publish_rate: 50.0
    cmd_vel_timeout: 0.5

    use_stamped_vel: false
