controller_manager:
  ros__parameters:
    update_rate: 200  # Hz. Make sure motor CAN status upload is >= this.

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_velocity_controller:
      type: forward_command_controller/ForwardCommandController

wheel_velocity_controller:
  ros__parameters:
    joints: ["wheel_joint"]
    interface_name: "velocity"
